# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyfringesGUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1197, 1006)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.shearplateCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.shearplateCheck.setMinimumSize(QtCore.QSize(78, 0))
        self.shearplateCheck.setMaximumSize(QtCore.QSize(78, 16777215))
        self.shearplateCheck.setChecked(True)
        self.shearplateCheck.setObjectName("shearplateCheck")
        self.gridLayout_4.addWidget(self.shearplateCheck, 3, 0, 1, 1)
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout_4.addWidget(self.graphicsView, 1, 2, 4, 1)
        self.graphicsView2 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView2.setObjectName("graphicsView2")
        self.gridLayout_4.addWidget(self.graphicsView2, 1, 3, 4, 1)
        self.GenFringes = QtWidgets.QPushButton(self.centralwidget)
        self.GenFringes.setMaximumSize(QtCore.QSize(91, 16777215))
        self.GenFringes.setObjectName("GenFringes")
        self.gridLayout_4.addWidget(self.GenFringes, 1, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 0, 0, 1, 1)
        self.numPix = QtWidgets.QLineEdit(self.centralwidget)
        self.numPix.setMaximumSize(QtCore.QSize(61, 16777215))
        self.numPix.setObjectName("numPix")
        self.gridLayout_4.addWidget(self.numPix, 0, 1, 1, 1)
        self.UpdateShear = QtWidgets.QPushButton(self.centralwidget)
        self.UpdateShear.setMinimumSize(QtCore.QSize(121, 0))
        self.UpdateShear.setMaximumSize(QtCore.QSize(121, 16777215))
        self.UpdateShear.setObjectName("UpdateShear")
        self.gridLayout_4.addWidget(self.UpdateShear, 6, 0, 1, 2)
        self.shearplatecomboBox = QtWidgets.QComboBox(self.centralwidget)
        self.shearplatecomboBox.setMaximumSize(QtCore.QSize(141, 16777215))
        self.shearplatecomboBox.setObjectName("shearplatecomboBox")
        self.shearplatecomboBox.addItem("")
        self.shearplatecomboBox.addItem("")
        self.shearplatecomboBox.addItem("")
        self.shearplatecomboBox.addItem("")
        self.shearplatecomboBox.addItem("")
        self.gridLayout_4.addWidget(self.shearplatecomboBox, 4, 0, 1, 2)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setMaximumSize(QtCore.QSize(161, 16777215))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.progressBar.setFont(font)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_4.addWidget(self.progressBar, 7, 0, 1, 2)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setMaximumSize(QtCore.QSize(174, 31))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_18 = QtWidgets.QLabel(self.frame_3)
        self.label_18.setMaximumSize(QtCore.QSize(31, 16))
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 0, 0, 1, 1)
        self.txtPV = QtWidgets.QLabel(self.frame_3)
        self.txtPV.setMaximumSize(QtCore.QSize(47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txtPV.setFont(font)
        self.txtPV.setObjectName("txtPV")
        self.gridLayout_2.addWidget(self.txtPV, 0, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.frame_3)
        self.label_19.setMaximumSize(QtCore.QSize(47, 16777215))
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 0, 2, 1, 1)
        self.txtRMS = QtWidgets.QLabel(self.frame_3)
        self.txtRMS.setMaximumSize(QtCore.QSize(16777215, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txtRMS.setFont(font)
        self.txtRMS.setObjectName("txtRMS")
        self.gridLayout_2.addWidget(self.txtRMS, 0, 3, 1, 1)
        self.gridLayout_4.addWidget(self.frame_3, 0, 2, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMaximumSize(QtCore.QSize(161, 201))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.frame_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 2, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.frame_2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.platewedge = QtWidgets.QLineEdit(self.frame_2)
        self.platewedge.setObjectName("platewedge")
        self.gridLayout_3.addWidget(self.platewedge, 1, 1, 1, 1)
        self.platesize = QtWidgets.QLineEdit(self.frame_2)
        self.platesize.setObjectName("platesize")
        self.gridLayout_3.addWidget(self.platesize, 3, 1, 1, 1)
        self.platethickness = QtWidgets.QLineEdit(self.frame_2)
        self.platethickness.setObjectName("platethickness")
        self.gridLayout_3.addWidget(self.platethickness, 0, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.frame_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 4, 0, 1, 1)
        self.beamsize = QtWidgets.QLineEdit(self.frame_2)
        self.beamsize.setObjectName("beamsize")
        self.gridLayout_3.addWidget(self.beamsize, 4, 1, 1, 1)
        self.plateindex = QtWidgets.QLineEdit(self.frame_2)
        self.plateindex.setObjectName("plateindex")
        self.gridLayout_3.addWidget(self.plateindex, 2, 1, 1, 1)
        self.gridLayout_4.addWidget(self.frame_2, 5, 0, 1, 2)
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(83, 125, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(83, 125, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(83, 125, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(83, 125, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.frame_5.setPalette(palette)
        self.frame_5.setAutoFillBackground(True)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_4.addWidget(self.frame_5, 5, 3, 3, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMaximumSize(QtCore.QSize(171, 328))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.label_14 = QtWidgets.QLabel(self.frame)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 0, 0, 1, 1)
        self.wavelength = QtWidgets.QLineEdit(self.frame)
        self.wavelength.setMaximumSize(QtCore.QSize(113, 16777215))
        self.wavelength.setObjectName("wavelength")
        self.gridLayout.addWidget(self.wavelength, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.numterms = QtWidgets.QLineEdit(self.frame)
        self.numterms.setMaximumSize(QtCore.QSize(113, 16777215))
        self.numterms.setObjectName("numterms")
        self.gridLayout.addWidget(self.numterms, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.piston = QtWidgets.QLineEdit(self.frame)
        self.piston.setMaximumSize(QtCore.QSize(113, 16777215))
        self.piston.setObjectName("piston")
        self.gridLayout.addWidget(self.piston, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.tiltx = QtWidgets.QLineEdit(self.frame)
        self.tiltx.setMaximumSize(QtCore.QSize(113, 16777215))
        self.tiltx.setObjectName("tiltx")
        self.gridLayout.addWidget(self.tiltx, 3, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.tilty = QtWidgets.QLineEdit(self.frame)
        self.tilty.setMaximumSize(QtCore.QSize(113, 16777215))
        self.tilty.setObjectName("tilty")
        self.gridLayout.addWidget(self.tilty, 4, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 5, 0, 1, 1)
        self.power = QtWidgets.QLineEdit(self.frame)
        self.power.setMaximumSize(QtCore.QSize(113, 16777215))
        self.power.setObjectName("power")
        self.gridLayout.addWidget(self.power, 5, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 6, 0, 1, 1)
        self.astigx = QtWidgets.QLineEdit(self.frame)
        self.astigx.setMaximumSize(QtCore.QSize(113, 16777215))
        self.astigx.setObjectName("astigx")
        self.gridLayout.addWidget(self.astigx, 6, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 7, 0, 1, 1)
        self.astigy = QtWidgets.QLineEdit(self.frame)
        self.astigy.setMaximumSize(QtCore.QSize(113, 16777215))
        self.astigy.setObjectName("astigy")
        self.gridLayout.addWidget(self.astigy, 7, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 8, 0, 1, 1)
        self.comax = QtWidgets.QLineEdit(self.frame)
        self.comax.setMaximumSize(QtCore.QSize(113, 16777215))
        self.comax.setObjectName("comax")
        self.gridLayout.addWidget(self.comax, 8, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 9, 0, 1, 1)
        self.comay = QtWidgets.QLineEdit(self.frame)
        self.comay.setMaximumSize(QtCore.QSize(113, 16777215))
        self.comay.setObjectName("comay")
        self.gridLayout.addWidget(self.comay, 9, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 10, 0, 1, 1)
        self.spherical = QtWidgets.QLineEdit(self.frame)
        self.spherical.setMaximumSize(QtCore.QSize(113, 16777215))
        self.spherical.setObjectName("spherical")
        self.gridLayout.addWidget(self.spherical, 10, 1, 1, 1)
        self.gridLayout_4.addWidget(self.frame, 2, 0, 1, 2)
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setEnabled(True)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(87, 240, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(87, 240, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(87, 240, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(87, 240, 110))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.frame_4.setPalette(palette)
        self.frame_4.setAutoFillBackground(True)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_4.addWidget(self.frame_4, 5, 2, 3, 1)
        self.testButton = QtWidgets.QPushButton(self.centralwidget)
        self.testButton.setObjectName("testButton")
        self.gridLayout_4.addWidget(self.testButton, 8, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1197, 38))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PyFringes"))
        self.shearplateCheck.setText(_translate("MainWindow", "Shear Plate"))
        self.GenFringes.setText(_translate("MainWindow", "Generate Fringes"))
        self.label_13.setText(_translate("MainWindow", "Resolution"))
        self.numPix.setText(_translate("MainWindow", "200"))
        self.UpdateShear.setText(_translate("MainWindow", "Update Shear Image"))
        self.shearplatecomboBox.setItemText(0, _translate("MainWindow", "Thor SI035 3-5mm beam"))
        self.shearplatecomboBox.setItemText(1, _translate("MainWindow", "Thor SI050 2.5-5mm beam"))
        self.shearplatecomboBox.setItemText(2, _translate("MainWindow", "Thor SI100 5-10mm beam"))
        self.shearplatecomboBox.setItemText(3, _translate("MainWindow", "Thor SI254 10-25.4mm beam"))
        self.shearplatecomboBox.setItemText(4, _translate("MainWindow", "Thor SI500 25.4-50mm beam"))
        self.label_18.setText(_translate("MainWindow", "PV"))
        self.txtPV.setText(_translate("MainWindow", "TextLabel"))
        self.label_19.setText(_translate("MainWindow", "RMS"))
        self.txtRMS.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "Plate Wedge"))
        self.label_15.setText(_translate("MainWindow", "Plate Index"))
        self.label_17.setText(_translate("MainWindow", "Plate Size"))
        self.label.setText(_translate("MainWindow", "Plate Thickness"))
        self.platewedge.setText(_translate("MainWindow", "10"))
        self.platesize.setText(_translate("MainWindow", "78"))
        self.platethickness.setText(_translate("MainWindow", "13"))
        self.label_16.setText(_translate("MainWindow", "Beam Size"))
        self.beamsize.setText(_translate("MainWindow", "50"))
        self.plateindex.setText(_translate("MainWindow", "1.457"))
        self.label_14.setText(_translate("MainWindow", "Wavelength"))
        self.wavelength.setText(_translate("MainWindow", "1.55"))
        self.label_3.setText(_translate("MainWindow", "Number of terms"))
        self.numterms.setText(_translate("MainWindow", "9"))
        self.label_4.setText(_translate("MainWindow", "Piston"))
        self.piston.setText(_translate("MainWindow", "0"))
        self.label_5.setText(_translate("MainWindow", "Tilt X"))
        self.tiltx.setText(_translate("MainWindow", "0"))
        self.label_6.setText(_translate("MainWindow", "Tilt Y"))
        self.tilty.setText(_translate("MainWindow", "0"))
        self.label_7.setText(_translate("MainWindow", "Power"))
        self.power.setText(_translate("MainWindow", "0"))
        self.label_8.setText(_translate("MainWindow", "Astig x"))
        self.astigx.setText(_translate("MainWindow", "0"))
        self.label_10.setText(_translate("MainWindow", "Astig y"))
        self.astigy.setText(_translate("MainWindow", "0"))
        self.label_9.setText(_translate("MainWindow", "Coma x"))
        self.comax.setText(_translate("MainWindow", "0"))
        self.label_12.setText(_translate("MainWindow", "Coma y"))
        self.comay.setText(_translate("MainWindow", "0"))
        self.label_11.setText(_translate("MainWindow", "Spherical"))
        self.spherical.setText(_translate("MainWindow", "0"))
        self.testButton.setText(_translate("MainWindow", "Test"))

